// "" designation value ommited
const designations: string[] = [
    "Affiliated Area",
    "Ecological & Historic Preserve",
    "International Historic Site",
    "International Park",
    "Memorial Parkway",
    "Memorial",
    "National Battlefield Park",
    "National Battlefield Site",
    "National Battlefield",
    "National Geologic Trail",
    "National Historic Area",
    "National Historic Site",
    "National Historic Trail",
    "National Historical Park and Ecological Preserve",
    "National Historical Park and Preserve",
    "National Historical Park",
    "National Historical Reserve",
    "National Lakeshore",
    "National Memorial",
    "National Military Park",
    "National Monument & Preserve",
    "National Monument and Historic Shrine",
    "National Monument",
    "National Park & Preserve",
    "National Park",
    "National Parks",
    "National Preserve",
    "National Recreation Area",
    "National Recreational River",
    "National Reserve",
    "National River & Recreation Area",
    "National River",
    "National Scenic River",
    "National Scenic Riverway",
    "National Scenic Riverways",
    "National Scenic Trail",
    "National Seashore",
    "National Wild and Scenic River",
    "National and State Parks",
    "Park",
    "Parkway",
    "Part of Colonial National Historical Park",
    "Part of Statue of Liberty National Monument",
    "Scenic & Recreational River",
    "Wild & Scenic River",
    "Wild River"
];

export default designations;