# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Cucumber Tests

on:
  push:
    branches:
    - "*"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - uses: nanasess/setup-chromedriver@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Setup chrome driver environment
      run: |
        sudo apt-get install -y xvfb
        sudo apt-get -y install xorg xvfb gtk2-engines-pixbuf
        sudo apt-get -y install dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable
        Xvfb -ac :99 -screen 0 1280x1024x16 &
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        google-chrome --disable-gpu --no-sandbox --disable-dev-shm-usage &
        command -v google-chrome
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run dev &
    - run: npm run cucumber
