# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Cucumber Tests

on:
  push:
    branches:
    - "*"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    services:
      selenium:
        image: selenium/standalone-chrome
        options: --shm-size=2gb

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Setup chrome driver environment
      run: |
        sudo apt-get update 
        sudo apt-get clean 
        sudo apt-get install -y which
        sudo apt-get install -y wget 
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
        sudo apt-get -y update 
        sudo apt-get install -y google-chrome-stable 
        VERSION=`google-chrome --version | egrep -o '[0-9]+.[0-9]+' | head -1` 
        npm i webdriver-manager@latest -D 
        npm i chromedriver --chromedriver_version=$VERSION -D 
        echo '-----------------------------<> <> <> <>'
        which chrome
        which google-chrome
        which chrome-driver
        which chromedriver
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run cucumber
